services:
  otel:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.86.0
    container_name: otel
    ports:
      - 4317:4317
      - 8888:8888
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml