apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  isDefault: false
  editable: false
  version: 1
  uid: loki
  jsonData:
    maxLines: 1000
    derivedFields:
    - datasourceUid: tempo
      matcherRegex: "traceID=(\\w+)"
      name: TraceID
      url: '$${__value.raw}'
      urlDisplayLabel: 'View Trace'
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
     tracesToLogsV2:
       customQuery: true
       datasourceUid: 'loki'
       query: '{$${__tags}} | json | trace_id = "$${__trace.traceId}"'
       tags:
         - key: 'service.name'
           value: 'container'
       filterByTraceID: true
       filterBySpanID: false