global:
  scrape_interval: 15s
  external_labels:
    cluster: demo

scrape_configs:
  - job_name: 'otel-collector'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['otelcol:9292']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']          